### PR TITLE
Add `throw` statement

### PR DESCRIPTION
**Pull request by pantras**
This really is great. 

The `throw` statement seems to be missing, so here it is. 

Feedback welcome.

### CODE REVIEW

**Comment by zverok** [comment]
There are two problems with this PR:

1. Probably, you haven't made yourself familiar with how this reference works. Most of the content is rendered directly from Ruby core docs, and ALL of the content in the main folder is autogenerated (by what lies in `_src` folder). In particular, how to generate the file you've changed, is described [here](https://github.com/rubyreferences/rubyref/blob/master/_src/config/structure.yml#L109), so, most of the content is from [here](https://github.com/ruby/ruby/blob/trunk/doc/syntax/control_expressions.rdoc)
2. Surprisingly for some, `throw` is not a keyword, but a `Kernel` method, so, in fact, it **is** referenced in [the appendix](https://rubyreferences.github.io/rubyref/appendix-a.html).

**Comment by pantras** [comment]
Thanks for your explanation. I was unsure which parts were generated, and which were hand-written. 
While we're at it, an index would have helped me find the `throw` method. Is there a plan to generate one ?

**Comment by zverok** [comment]
@pantras Sorry for long delay with answer, I was on vacation and Internet-deprivated :)
Yes, the global index is one of things that is obviously missing. But the problem is, to this moment I can't decide what should go to this index/how it should be structured. Just all the keywords and class and method names?.. Some additional important concepts?.. How to choose?

**Comment by andrykonchin** [comment]
@zverok At least you can follow the structure of draft of the [Ruby ISO standard](https://www.ipa.go.jp/files/000011432.pdf) or even [Matz' book](https://www.amazon.com/Ruby-Programming-Language-Everything-Need/dp/0596516177)

And if you decide to add something to [language related articles](https://github.com/rubyreferences/rubyref/tree/master/language) please take a look at RubySpec project and test cases [here](https://github.com/ruby/spec/tree/master/language)

**Comment by pantras** [comment]
I would start small, with Ruby keywords, class and method names.  Having to know the nature of something to be able find it is a problem and hinders people using the Ruby Reference. 
IMHO, you cannot afford to omit concepts in the index.

**Comment by zverok** [comment]
That's probably right, but this kind of index is a) huge and b) already available at the regular docs: https://ruby-doc.org/core-2.5.0/ (under Classes/Methods headings). My "rule of thumb" for this reference is "something that could possibly be useful if printed (or stored in EPUB and read from smartphone)". List of _all_ methods from _all_ core & stdlib classes is hardly useful resource without complex dynamic navigation, there are just too much (and particular method docs, except vital Kernel methods, are omitted from this reference, so the index is just nowhere to point).

So, I agree _some_ kind of index could be useful, but the _exact nature_ of it is still a bit questionable for me.

**Pull request closed without merging**
